import { PERMISSIONS, type PermissionKey } from "./permission.keys.js";

export const DEFAULT_ROLE_NAMES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
  VIEWER: "VIEWER"
} as const;

export type DefaultRoleName = (typeof DEFAULT_ROLE_NAMES)[keyof typeof DEFAULT_ROLE_NAMES];

export const DEFAULT_ROLE_PERMISSIONS: Record<DefaultRoleName, PermissionKey[]> = {
  OWNER: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_DELETE,

    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE_ROLE,
    PERMISSIONS.MEMBER_REMOVE,

    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_UPDATE,
    PERMISSIONS.ROLE_DELETE,
    PERMISSIONS.ROLE_ASSIGN_PERMISSION,

    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.SCAN_CREATE,
    PERMISSIONS.SCAN_READ,
    PERMISSIONS.SCAN_IMPORT,

    PERMISSIONS.ISSUE_READ,
    PERMISSIONS.ISSUE_UPDATE_STATUS,
    PERMISSIONS.ISSUE_COMMENT,

    PERMISSIONS.ARTIFACT_READ,
    PERMISSIONS.ARTIFACT_UPLOAD,
    PERMISSIONS.ARTIFACT_DELETE,

    PERMISSIONS.AI_ANALYZE,

    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,

    PERMISSIONS.API_MONITOR_READ,
    PERMISSIONS.API_MONITOR_MANAGE
  ],

  ADMIN: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_UPDATE,

    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE_ROLE,
    PERMISSIONS.MEMBER_REMOVE,

    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_UPDATE,
    PERMISSIONS.ROLE_ASSIGN_PERMISSION,

    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.SCAN_CREATE,
    PERMISSIONS.SCAN_READ,
    PERMISSIONS.SCAN_IMPORT,

    PERMISSIONS.ISSUE_READ,
    PERMISSIONS.ISSUE_UPDATE_STATUS,
    PERMISSIONS.ISSUE_COMMENT,

    PERMISSIONS.ARTIFACT_READ,
    PERMISSIONS.ARTIFACT_UPLOAD,
    PERMISSIONS.ARTIFACT_DELETE,

    PERMISSIONS.AI_ANALYZE,

    PERMISSIONS.API_MONITOR_READ,
    PERMISSIONS.API_MONITOR_MANAGE
  ],

  MEMBER: [
    PERMISSIONS.WORKSPACE_READ,

    PERMISSIONS.MEMBER_READ,

    PERMISSIONS.ROLE_READ,

    PERMISSIONS.PROJECT_READ,

    PERMISSIONS.SCAN_CREATE,
    PERMISSIONS.SCAN_READ,

    PERMISSIONS.ISSUE_READ,
    PERMISSIONS.ISSUE_UPDATE_STATUS,
    PERMISSIONS.ISSUE_COMMENT,

    PERMISSIONS.ARTIFACT_READ,
    PERMISSIONS.ARTIFACT_UPLOAD,

    PERMISSIONS.AI_ANALYZE,

    PERMISSIONS.API_MONITOR_READ
  ],

  VIEWER: [
    PERMISSIONS.WORKSPACE_READ,

    PERMISSIONS.MEMBER_READ,

    PERMISSIONS.ROLE_READ,

    PERMISSIONS.PROJECT_READ,

    PERMISSIONS.SCAN_READ,

    PERMISSIONS.ISSUE_READ,

    PERMISSIONS.ARTIFACT_READ,

    PERMISSIONS.API_MONITOR_READ
  ]
};
